#spring:
#  datasource:
#    username: postgres
#    password: 0707
#    url: jdbc:postgresql://localhost:5432/postgres
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create